# Prometheus config

prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: infralan

prometheus_scrape_configs:
  - job_name: "prometheus"    # Custom scrape job, here using `static_config`
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:9090"