# site.yml
---
- hosts: all # Indicate hosts this applies to (host or group name)
  tasks:
    - name: Install paramiko
      pip:
        name: paramiko
        executable: pip3
    - name: Install jmespath
      pip:
        name: jmespath
        executable: pip3
  roles: # Enumerate roles to be applied
    - bertvv.rh-base
    - cloudalchemy.node-exporter
  vars:
    rhbase_firewall_allow_ports:
      - 53/udp
      - 80/tcp
      - 9100/tcp

- hosts: srv010
  roles:
    - geerlingguy.mysql
    - bertvv.httpd
    - bertvv.wordpress

- hosts: srv001
  roles:
    - bertvv.bind

- hosts: srv004
  roles:
  - cloudalchemy.prometheus
  
- hosts: srv003
  roles:
    - bertvv.dhcp

