# site.yml
---
- hosts: all # Indicate hosts this applies to (host or group name)
  roles: # Enumerate roles to be applied
    - bertvv.rh-base
- hosts: srv010
  roles:  
    - geerlingguy.mysql
    - bertvv.httpd
    - bertvv.wordpress
- hosts: srv001
  roles:
    - bertvv.bind

